name: main_repo

on:
  workflow_dispatch:
  
  push:
    branches:
      - "chore/main"
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive